# roles/common/admin.yml
# vim: ft=yaml
#
# Settings regarding the admin user
---
- name: Make sure users from the wheel group can use sudo
  lineinfile:
    dest=/etc/sudoers.d/wheel
    state=present
    create=yes
    regexp='^%wheel'
    line='%wheel ALL=(ALL) ALL'
    validate='visudo -cf %s'
  tags:
    - common
    - admin

- name: Set attributes of sudo configuration file for wheel group
  file:
    path=/etc/sudoers.d/wheel
    owner=root
    group=root
    mode=0440
  tags:
    - common
    - admin

- name: Set up SSH key for admin user
  authorized_key:
    user={{ admin_user }}
    key="{{ ssh_pubkey }}"
  when: admin_user is defined
  tags:
    - common
    - admin

