# ansible/roles/common/tasks/config.yml
---

- name: Check if Nano is installed
  stat: path=/usr/bin/nano
  register: usr_bin_nano
  tags:
    - common
    - config

- name: Install Nanorc
  copy:
    src=etc_nanorc
    dest=/etc/nanorc
    owner=root
    group=root
    mode=0644
  when: usr_bin_nano.stat.exists
  tags:
    - common
    - config

