# roles/common/tasks/users.yml
# vi: ft=yaml
#
# Create groups and users on the system
---
- name: Add groups
  group:
    name={{ item }}
    state=present
  with_items: user_groups
  when: user_groups is defined
  tags:
    - common
    - users

- name: Add users
  user:
    name={{ item.name }}
    state=present
    comment={{ item.comment }}
    groups={{ item.groups }}
    home={{ item.home }}
    password={{ item.password }}
  with_items: users
  when: users is defined
  tags:
    - common
    - users

